src/validations.rs

Fix the luhn algorithm for Amex cards, by changing the ordering used in the luhn check algorithm

fix(luhn): fix the check by reversing ordering

---

src/routes/data.rs
src/routes/data/transformers.rs
src/routes/data/types.rs

Currently we are taking the hash of entire card details (payment method data) for card duplication check. In this case if a add card request is made for same card number but with a different card holder name, cvv or expiry it would pass the card duplication check and the card would get added even though the card number is same. 
So this pr treats the card number as a unique field and performs the duplication based on it.
Test case :-
1) Payment method create.
2) Payment method create for same merchant and customer, change `card_holder_name` keeping the the card number same.
3) Locker db still has only one card inserted in locker table.
4) Also there is only one entry in the hash table as well.

feat(router): use only card number for card duplication check

---

src/error.rs
src/error/container.rs
src/error/custom_error.rs
src/error/transforms.rs
src/storage/caching/hash_table.rs
src/storage/caching/merchant.rs
src/storage/db.rs

There is an issue with the consistency of nested types for caching, the issue lies in the way `Deref` works and how the traits are implemented.
example:
```rust
struct A;
struct B;
struct C;
trait MyTrait {}
impl MyTrait for C {}
impl Deref for A {
type Target = B;
}
impl Deref for B {
type Target = C;
}
fn handle<X, Y>(data: X)
where
X: Deref<Target = Y>,
Y: MyTrait
{}
```
In this scenerio struct of type `B` can be passed to the function `handle` without any issue, but when trying to pass `A` you will get an error:
```
error[E0277]: the trait bound `B: MyTrait` is not satisfied
--> src/main.rs:112:5
|
112 |     handle(A);
|     ^^^^^^ the trait `MyTrait` is not implemented for `B`
|
= help: the trait `MyTrait` is implemented for `C`
note: required by a bound in `handle`
--> …
```

chore: fix caching issue for conditional merchant creation

---

Cargo.lock
Cargo.toml
build.rs

This PR updates the build script code to obtain cargo workspace member package names to use a better and more deterministic way to do so. 
Previously, we used to perform string manipulation on the package ID format (obtained from the `workspace_members` field in `cargo metadata --format-version=1`), and the package ID format was not stabilized (until recently). The package ID format has been [stabilized](https://github.com/rust-lang/cargo/pull/12914) in Rust 1.77, and the stabilized format breaks our existing build scripts. This PR updates the build script code to instead obtain the workspace member package names using the [`Metadata::workspace_packages()`](https://docs.rs/cargo_metadata/0.18.1/cargo_metadata/struct.Metadata.html#method.workspace_packages) method that the `cargo_metadata` …

build: obtain workspace member package names from cargo_metadata more deterministically

---

benches/luhn-test.rs
src/routes/data/types.rs
src/routes/health.rs
src/storage/types.rs
src/validations.rs

This PR addresses the non-digit character cases in card number validation and raises an appropriate error if fails. 
This PR also includes min and max length check for card number.
1. Card number containing some invalid character
2. `109` passes luhn but fails the card length constraint 
3. Invalid card number not passing luhn

fix: address non-digit character cases in card number validation

---

src/app.rs
src/error/container.rs
src/routes/key_custodian.rs
src/utils.rs

This PR records the `tenant_id` header field in each request's trace. This PR also maps the CryptoError::DecryptionError to ApiError::DecryptingKeysFailed

refactor: record `tenant_id` header field in request trace

---

migrations/2024-06-21-105740_remove_tenant_id_column_from_all_tables/down.sql
migrations/2024-06-21-105740_remove_tenant_id_column_from_all_tables/up.sql
src/routes/data.rs
src/routes/data/transformers.rs
src/storage.rs
src/storage/caching/merchant.rs
src/storage/db.rs
src/storage/schema.rs
src/storage/types.rs

This PR removes the `tenant_id` column from all the existing tables
Made a save card payment from hyperswitch - 
DB schema after `tenant_id` removal - 
1. Merchant table 
2. Locker table

refactor: remove `tenant_id` column from all existing tables

---

Cargo.toml
migrations/2024-07-02-071458_v2-migrations/down.sql
migrations/2024-07-02-071458_v2-migrations/up.sql
src/lib.rs
src/storage.rs
src/storage/caching/fingerprint.rs
src/storage/db.rs
src/storage/schema.rs
src/storage/types.rs

This PR adds db migrations required for v2
* Rename fingerprint column names
* Add `vault` table for storing data 
* Add `entity` table for storing `key_id` of encryption service for each entity

refactor: add db migrations for v2

---

Cargo.lock
Cargo.toml
config.example.toml
config/development.toml
config/docker-configuration.toml
src/api_client.rs
src/app.rs
src/config.rs
src/crypto.rs
src/crypto/keymanager.rs
src/crypto/keymanager/types.rs
src/error.rs
src/error/container.rs
src/error/custom_error.rs
src/error/transforms.rs
src/lib.rs
src/routes/data.rs
src/routes/key_custodian.rs
src/storage.rs
src/storage/caching.rs
src/storage/caching/entity.rs
src/storage/caching/fingerprint.rs
src/storage/caching/hash_table.rs
src/storage/caching/merchant.rs
src/storage/consts.rs
src/storage/db.rs
src/storage/types.rs
src/tenant.rs

This PR integrates secret manager and makes use of it to store the entity dek.
Keeping in mind about the old dek's, this PR for now calls secret manager to store dek, only when new merchant hits add request. This is done to keep the number of merchant dek's to be migrated in future fixed. 
During add request, if new merchant, create a merchant dek in merchant table and also call secret manager to transfer the created dek to the service.

feat: integrate a secret manager

---

Cargo.lock
Cargo.toml
src/app.rs

This PR bumps below dependencies:
* diesel - 2.2.3
* diesel_async - 0.5.0
* serde_json - 1.0.127
This PR also bumps MSRV to 1.78 as diesel MSRV is 1.78. Pinned `masking` crate dependency to git tag `v1.111.1`

build(deps): bump dependencies to supported versions

---

config/development.toml
src/app.rs
src/config.rs
src/routes/data.rs
src/routes/health.rs
src/routes/key_custodian.rs
src/routes/key_migration.rs
src/tenant.rs

Add support for providing separate `schema` to support granularity when choosing the underlying database schema with respect to the tenant.

chore: add support for schema as a key in tenant secrets

---

Cargo.lock
Cargo.toml
src/logger/setup.rs

Add support for `console-subscriber` making monitoring of tasks and resources more convenient.

feat(logging): add `console-subscriber` to support monitoring on tokio

---

config/development.toml
docs/openapi-v2/spec.yml
src/app.rs
src/custom_extractors.rs
src/routes/data.rs
src/routes/data/crypto_operation.rs
src/routes/data/transformers.rs
src/routes/data/types.rs
src/routes/routes_v2/data.rs
src/routes/routes_v2/data/types.rs
src/storage/consts.rs
src/storage/storage_v2.rs
src/storage/storage_v2/db.rs
src/storage/storage_v2/types.rs
src/storage/types.rs
src/utils.rs

This pr adds the api handler to `/add` `/retrieve` and `/delete`  `v2` endpoints.
Also adds `/fingerprint` under `v2` that uses the same function as v1 just for the unification purpose .
test case
-> Add data
```
curl --location 'http://localhost:3030/api/v2/vault/add' \
--header 'x-tenant-id: hyperswitch' \
--header 'Content-Type: application/json' \
--data '{
"entity_id": "hyperswitch",
"vault_id": "123456789",
"data": {
"card_number": "4111111111111111",
"name_on_card": "hyperswitch vaut"
}
}'
```
```
{
"entity_id": "hyperswitch",
"vault_id": "123456789"
}
```
-> retrieve data
```
curl --location 'http://localhost:3030/api/v2/vault/retrieve' \
--header 'x-tenant-id: hyperswitch' \
--header 'Content-Type: application/json' \
--data '{
"entity_id": "hyperswitch",
"vault_id": "123456789" …
```

feat(router): add support v2 `/add` `/retrieve` `/delete` api handler

---

Cargo.toml

This PR adds the `external_key_manager_mtls` feature flag to `release` features

chore: add `external_key_manager_mtls` feature flag to release

---

Cargo.toml
src/crypto/keymanager.rs
src/storage/consts.rs

This pull request includes several changes to the `src/crypto/keymanager.rs` file, primarily focusing on the introduction of base64 encoding for authorization headers and the use of constants for the base64 engine. Below is a summary of the most important changes:
* Added the `base64::Engine` import to enable base64 encoding functionality.
* Introduced the `BASE64_ENGINE` constant from `consts` to standardize the base64 encoding process.
* Modified the header generation to include a base64 encoded authorization header by splitting the master key, encoding its halves in hex, and then combining and encoding them in base64.

feat(keymanager): add support for sending master key to key manager

---

Cargo.toml

This pull request includes a change to the `Cargo.toml` file to update the dependencies for the `external_key_manager_mtls` feature.
Dependency updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L19-R21): Added `reqwest/rustls-tls` to the `external_key_manager_mtls` feature to ensure it includes the necessary dependencies for mutual TLS support.

fix(mtls): fix provider import for mtls

---

config/development.toml
src/app.rs
src/error.rs
src/logger/formatter.rs
src/logger/storage.rs
src/storage/consts.rs
src/storage/db.rs
src/utils.rs

1. `tenant-id` and `request-id` in console logging - 
2. `tenant-id` and `request-id` in json logging - 
3. removed `map_err` in some db methods and used `change_error`, hence getting whole error stack

refactor: record `tenant_id` and `request_id` from header in the trace span

---

src/logger/setup.rs

This pull request includes a change to the `setup` function in the `src/logger/setup.rs` file to enhance the logging configuration by adding a filter to the logging layer.
Logging configuration improvement:
* [`src/logger/setup.rs`](diffhunk://#diff-aae7f06039eaec6c526b32b89c2b9abc129b658918295df039d3abd2b3507adfL58-R59): Modified the `setup` function to include a filter (`console_filter`) in the `FormattingLayer` initialization for the JSON log format.

fix: add console filters for json logs

---

src/crypto/keymanager/external_keymanager/utils.rs

This pull request includes updates to the `src/crypto/keymanager/external_keymanager/utils.rs` file to enhance the security and functionality of the key manager header.
Security improvements:
* [`src/crypto/keymanager/external_keymanager/utils.rs`](diffhunk://#diff-1f0c9447f190009fcda42401b68cdccad713002f46f1f29a6d7d013c45b56eaeL5-R7): Added the `Mask` import from the `masking` crate and used the `into_masked` method to mask the `broken_master_key` in the `get_key_manager_header` function. [[1]](diffhunk://#diff-1f0c9447f190009fcda42401b68cdccad713002f46f1f29a6d7d013c45b56eaeL5-R7) [[2]](diffhunk://#diff-1f0c9447f190009fcda42401b68cdccad713002f46f1f29a6d7d013c45b56eaeL23-R28)
Functionality enhancements:
* [`src/crypto/keymanager/external_keymanager/utils.rs`](diffhunk://#diff-1f0c9447f1900 …

chore: add x-tenant-id in encryption service call

---

src/logger/formatter.rs
src/logger/storage.rs

This pull request includes changes to the logging mechanism in the `src/logger` module. The most important changes involve replacing the `tracing::warn!` macro with `eprintln!` for logging reserved entries.
Changes to logging mechanism:
* [`src/logger/formatter.rs`](diffhunk://#diff-0d16e777a61aacf0f5983497f7d7f32ec199d3fec79daec73b95124989a255cdL195-R195): Replaced `tracing::warn!` with `eprintln!` for logging attempts to add reserved entries to the logs.
* [`src/logger/storage.rs`](diffhunk://#diff-a333b12c5a5910d99aafee2ee90bd49962457a2c7bd29b5b065443d1deebc160L34-R34): Replaced `tracing::warn!` with `eprintln!` for logging reserved entries when recording values.

fix(logger): remove warn from subscriber

---

Cargo.lock

Update transitive dependency openssl  from version = "0.10.66" to version = "0.10.70" and openssl-sys from version = "0.9.103" to version = "0.9.105"

build(deps): bump `openssl` from 0.10.66 to 0.10.70

---

src/config.rs

This pull request includes a minor change to the `GlobalConfig` implementation in the `src/config.rs` file. The change modifies an error message to accurately reflect the context of the public key.
* [`src/config.rs`](diffhunk://#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecdL276-R276): Changed the error message in the `change_context` method from "master_key" to "public_key" to accurately describe the context of the error.

fix error message in kms decryption

---

Cargo.toml
src/bin/locker.rs
src/crypto/secrets_manager/managers/hcvault/implementers.rs
src/error/transforms.rs

This pull request introduces a new feature flag, `dev`, in the `Cargo.toml` file to facilitate development-specific configurations.
Key change:
* Added a `dev` feature flag in `Cargo.toml` with dependencies including `kms-aws`, `middleware`, `key_custodian`, `limit`, `kms-hashicorp-vault`, and `caching`. This is likely intended to streamline development workflows by grouping commonly used features for development. (`[Cargo.tomlR13](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R13)`)

refactor: add dev feature flag
